config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  devise_for :users
  resources :categories
  resources :stores
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'index/about'
  root 'index#index'

  namespace :charts do
    get "byStore"
    get "byCategory"
    get "byMonth"
    get "byWeek"
  end

end

app/models/store.rb
class Store < ApplicationRecord
    belongs_to :user
    has_many :transactions
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: %i[ show edit update destroy ]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  # GET /stores or /stores.json
  def index
    @stores = Store.where(user_id: current_user.id)
  end

  # GET /stores/1 or /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = current_user.stores.build
    #Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores or /stores.json
  def create
    #@store = Store.new(store_params)
    @store = current_user.stores.build(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: "Store was successfully created." }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1 or /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: "Store was successfully updated." }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1 or /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: "Store was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    #checks for the store by looking at the associated ids in the user
    @store = current_user.stores.find_by(id: params[:id])
    redirect_to stores_path, notice: "Not authorised" if @store.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def store_params
      params.require(:store).permit(:name, :location, :store_type, :user_id)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
        <% store.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.text_field :name, class:"form-control", placeholder:"Store name" %>
  </div>

  <div class="field mb-3">
    <%= form.text_field :location, class:"form-control", placeholder:"Location" %>
  </div>

  <div class="field mb-3">
    <%= form.text_field :store_type, class:"form-control", placeholder:"Type" %>
  </div>

   <div class="field mb-3">
    <% form.number_field :user_id, id: :stores_user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>
<br/>
<%= link_to 'Show', @store, class:"btn btn-secondary" %>
<%= link_to 'Back', stores_path, class:"btn btn-secondary" %>

app/views/stores/index.html.erb
<h1>Stores list</h1>

<table class="table table-sm table-hover table-bordered table-striped">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Store type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.location %></td>
        <td><%= store.store_type %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Store', new_store_path, class: "btn btn-primary" %>

app/views/stores/new.html.erb
<h1>Add New Store</h1>

<%= render 'form', store: @store %>
<br>
<%= link_to 'Back', stores_path, class:"btn btn-secondary"%>

app/views/stores/show.html.erb
<div class="h-100 p-5 bg-light border rounded-3">
  <h2>
    <%= @store.name %> - 
    <%= @store.location %>
  </h2>

  <p>
    <strong>Store type:</strong>
    <%= @store.store_type %>
  </p>

  <%= link_to 'Edit', edit_store_path(@store), class:"btn btn-outline-secondary" %>
  <%= link_to 'Back', stores_path, class:"btn btn-outline-secondary" %>

</div>