config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  devise_for :users
  resources :categories
  resources :stores
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'index/about'
  root 'index#index'

  namespace :charts do
    get "byStore"
    get "byCategory"
    get "byMonth"
    get "byWeek"
  end

end

app/views/index/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Household Spending', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Transactions', transactions_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Stores', stores_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Categories', categories_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'About', index_about_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit profile',  edit_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign out',  destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
        <% else %>         
          <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign in',  new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/index/about.html.erb
<h2>About this application</h2 >

<p>This was written during my time at Code Chrysalis - a full time full stack bootcamp in Tokyo.</p>
<p>The aim was to provide a way to track spending within my household based on categories, stores, and dates</p>

app/views/index/index.html.erb
<h2>Welcome <%= current_user.name %></h2>