config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  devise_for :users
  resources :categories
  resources :stores
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'index/about'
  root 'index#index'

  namespace :charts do
    get "byStore"
    get "byCategory"
    get "byMonth"
    get "byWeek"
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  include TransactionsHelper
  before_action :set_transaction, only: %i[ show edit update destroy ]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  # GET /transactions or /transactions.json
  def index
    if params[:month].present?
      session[:selectedMonth] = params[:month]
      @pagy, @transactions = pagy(Transaction.where("date_trunc('month', created_at)=? AND user_id=?", params[:month]+"-01", current_user.id), items: 10)
    else
      session[:selectedMonth] = Time.now.strftime("%Y-%m")
      puts("no month", session[:selectedMonth])
      @pagy, @transactions = pagy(Transaction.where("date_trunc('month', created_at)=? AND user_id=?", session[:selectedMonth]+"-01", current_user.id), items: 10)
    end
  end

  # GET /transactions/1 or /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = current_user.transactions.build
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions or /transactions.json
  def create
    @transaction = current_user.transactions.build(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: "Transaction was successfully created." }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: "Transaction was successfully updated." }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: "Transaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    #checks for the store by looking at the associated ids in the user
    @transaction = current_user.transactions.find_by(id: params[:id])
    redirect_to transactions_path, notice: "Not authorised" if @transaction.nil?
  end

  #chart paths



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:transaction).permit(:user_id, :store_id, :category_id, :amount)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
    include Pagy::Frontend
    def calculateTotal
        Transaction.where("date_trunc('month', created_at)=? AND user_id=?", session[:selectedMonth]+"-01", current_user.id).sum(:amount)
    end
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <% form.text_field :user_id %>
  </div>

  <div class="field input-group mb-3">
    <%= form.collection_select :store_id, Store.where(user_id: current_user.id).order(:name), :id, :name, {prompt: "Choose a store"}, {class:"form-select", aria:"multiple select example"} %>
  </div>

  <div class="field mb-3">
      <%= form.collection_select :category_id, Category.where(user_id: current_user.id).order(:name), :id, :name, {prompt: "Choose a category"}, {class:"form-select", aria:"multiple select example"} %>
  </div>

  <div class="field mb-3">
    <%= form.label :amount %>
    <%= form.number_field :amount, class:"form-control", min: 1, placeholder:@hint_value %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-success"  %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>
<br/>
<%= link_to 'Show', @transaction, class:"btn btn-secondary" %>
<%= link_to 'Back', transactions_path, class:"btn btn-secondary" %>

app/views/transactions/index.html.erb
<h1>Transactions</h1>

<%= form_tag transactions_path, method: :get do %>
  <div class="input-group mb-3">
    <%= label :month, "Filter by month:", class:"input-group-text" %>
    <%= month_field_tag :month, params[:month], class: "form-control", selected: session[:selectedMonth] %>
    <%= submit_tag "Filter", class: "btn btn-secondary" %>
  </div>
  <% end %>

<br/>
<table class="table table-sm table-hover table-bordered table-striped">
  <thead class="table-dark" onChange=>
    <tr>
      <th>User</th>
      <th>Store</th>
      <th>Category</th>
      <th>Amount</th>
      <th>Date</th>
      <th colspan="8"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.user.name %></td>
        <td><%= "#{transaction.store.name} - #{transaction.store.location}" %></td>
        <td><%= transaction.category.name %></td>
        <td><%= "¥#{transaction.amount}" %></td>
        <td><%= "#{transaction.created_at.strftime("%Y-%m-%d")}" %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%== pagy_bootstrap_nav(@pagy) %>
<br/>
<%= link_to 'New Transaction', new_transaction_path, class: "btn btn-primary" %>
<br/>
<br/>
<p><%= "This months total spending: ¥#{format('%.d',calculateTotal)}" %></p>

<br/>

<h1>Charts</h1>

<div class="container">
<div class="d-flex justify-content-center">
  <%= column_chart "/charts/byStore", prefix: "¥", title: "Spending by store", class:" p-2 bg-light", library: {responsive: true} %>
  <%= column_chart "/charts/byCategory", prefix: "¥", title: "Spending by category", class:" p-2 bg-light", library: {responsive: true}  %>
  </div>
  <div class="d-flex justify-content-center">
    <%= line_chart "/charts/byWeek", prefix: "¥",title: "Spending by week",class:" p-2 bg-light", library: {responsive: true}  %>
    <%= column_chart "/charts/byMonth",prefix: "¥",title: "Spending by month" ,class:" p-2 bg-light", library: {responsive: true} %>
  </div>
</div>

<br><br>

app/views/transactions/new.html.erb
<h1>Add New Transaction</h1>

<%= render 'form', transaction: @transaction %>
<br/>
<%= link_to 'Back', transactions_path, class:"btn btn-secondary" %>

app/views/transactions/show.html.erb
<div class="h-100 p-5 bg-light border rounded-3">
  <h4>
    <%= "#{@transaction.user.name}\nspent ¥#{@transaction.amount}\nat #{@transaction.store.name} - #{@transaction.store.location}\non #{@transaction.created_at.strftime('%Y/%m/%d')}"%>
  </h4>

  <%= link_to 'Edit', edit_transaction_path(@transaction), class:"btn btn-outline-secondary" %> |
  <%= link_to 'Back', transactions_path, class:"btn btn-outline-secondary" %>
</div>